#!/bin/bash

#SBATCH --job-name=extract_kw_embeddings
#SBATCH --account=project_462000353
#SBATCH --partition=dev-g
#SBATCH --mem=192G
#SBATCH --time=00:10:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gpus-per-node=1
#SBATCH --output=slurm-logs/array_%A_%a.out
#SBATCH --error=slurm-logs/array_%A_%a.err
#SBATCH --array=3

# If run without sbatch, invoke here
if [ -z "$SLURM_JOB_ID" ]; then
	sbatch "$0" "$@"
	exit
fi

# See http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail

# Make logging a bit easier
mkdir -p slurm-logs
rm -f "slurm-logs/current_${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.err"
rm -f "slurm-logs/current_${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.out"
ln -s "array_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.err" "slurm-logs/current_${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.err"
ln -s "array_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.out" "slurm-logs/current_${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.out"

# Load the path parameters from the files
# The first line of paths.txt should contain, in order:
# 1. The filtered dataset containing the keywords related to documents
# 2. The model directory
# 3. Output data folder (does not need to exist)
read -r DATASET MODELS EMBEDDINGS < paths-extract-embs.txt

# You can feed different hyperparameter combinations to the script using this
# Currently, only language is supported
read -r LANG < <(sed -n "$((SLURM_ARRAY_TASK_ID + 1))p" param-grid-data-prep.txt) # TODO: perhaps expand param grid, extract from different file

# Load the Python environment
module purge > /dev/null 2>&1 # Get rid of boilerplate stderr
module use /appl/local/csc/modulefiles > /dev/null 2>&1
module load pytorch > /dev/null 2>&1

# Run the script for each fold
#for i in $(seq 1 10); do
for i in $(seq 1); do
	# Run the Python script with the parameters
	srun --ntasks=1 python -u extract_embeddings.py \
		"$DATASET" \
		"$MODELS" \
		"$EMBEDDINGS" \
		"$LANG" \
		"fold_${i}" &
done

wait

# Walltime statistics
sacct -o jobid,elapsed -j "${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}"

